### PR TITLE
Weekdays only

### PR DESCRIPTION
**Pull request by nzack**
only adds schedules during the week;

### CODE REVIEW

**Comment by JasonGhent** [comment]
@nzack since this is a long-running process with no tests, is there any way to test it without deploying this change? Would be awesome to get this in before the weekend!

**Comment by jjshoe** [comment]
lgtm

**Comment by nzack** [comment]
[Checklist auto-comment] `Add or update unit and integration tests`: :+1:

**Comment by nzack** [comment]
[Checklist auto-comment] `Verify no security issues are being introduced`: :+1:

**Comment by nzack** [comment]
[Checklist auto-comment] `Add or update documentation`: :+1:

**Pull request merged**
